clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    # 64 bit builds
    - GHCVER: "9.6.1"
      CHOCOPTS: --no-progress
    - GHCVER: "9.4.4"
      CHOCOPTS: --no-progress
    - GHCVER: "9.2.7"
      CHOCOPTS: --no-progress

cache:
- "C:\\SR"

install:
 - "choco install -y ghc --version %GHCVER% %CHOCOPTS%"
 - "choco install -y cabal %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\ghc\\ghc-%GHCVER%:C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -v"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "echo packages:. > cabal.project"
 - "cabal %CABOPTS% new-build -j1 all"
